# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 79c22a8e328fb8717eab832091b3b60b633c2d508ee2cf942c60eda0f6d49f282bb45b2069029309a0d94d2d4cbb13e916876c2116ca76df5fcc7a86d475cfd2

test:
  secret_key_base: b2282e27b7f0fd37b3395153e8b1b9a8030a5da3920dd83f8ae2756cdd072316808b3a0a36b211f3367edc84982f46052f37cbba34eb854f5ebf6f9e74642933

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
